apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: conjur-secretstore
  namespace: {{ .Values.namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: conjur-secretstore
    kind: SecretStore
  target:
    name: conjur-secrets
  data:
  - secretKey: DB_HOSTNAME
    remoteRef:
      key: {{ .Values.DB_HOSTNAME }}
  - secretKey: DB_NAME
    remoteRef:
      key: {{ .Values.DB_NAME }}
  - secretKey: DB_UNAME
    remoteRef:
      key: {{ .Values.DB_UNAME }}
  - secretKey: DB_PWD
    remoteRef:
      key: {{ .Values.DB_PWD }}
