---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: db-credentials
spec:
  provider: conjur
  parameters:
    conjur.org/configurationVersion: 0.1.0
    account: conjur
    applianceUrl: {{CONJUR_URL}}
    authnId: authn-jwt/{{JWT_SERVICE_ID}}
    sslCertificate: | {{CONJUR_CERT}}
    secrets: |
      - DB_HOSTNAME: data/vault/{{SAFE_NAME}}/{{MYSQL_ACCOUNT_NAME}}/address
      - DB_NAME: data/vault/{{SAFE_NAME}}/{{MYSQL_ACCOUNT_NAME}}/Database
      - DB_UNAME: data/vault/{{SAFE_NAME}}/{{MYSQL_ACCOUNT_NAME}}/username
      - DB_PWD: data/vault/{{SAFE_NAME}}/{{MYSQL_ACCOUNT_NAME}}/password
