# K8s Secret manifest which maps Conjur variable IDs
# to secret keys. The Conjur K8s Secrets Provider will
# update the secret with keys and the current values of
# the Conjur variables.
---
apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
type: Opaque
stringData:
  conjur-map: |-
    DB_HOSTNAME: data/vault/{{SAFE_NAME}}/{{MYSQL_ACCOUNT_NAME}}/address
    DB_NAME: data/vault/{{SAFE_NAME}}/{{MYSQL_ACCOUNT_NAME}}/Database
    DB_UNAME: data/vault/{{SAFE_NAME}}/{{MYSQL_ACCOUNT_NAME}}/username
    DB_PWD: data/vault/{{SAFE_NAME}}/{{MYSQL_ACCOUNT_NAME}}/password
