apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: conjur-secretstore
spec:
  provider:
    conjur:
      # Service URL
      url: {{CONJUR_URL}}
      caBundle: "{{CONJUR_CERT_B64}}"
      auth:
        jwt:
          # conjur account
          account: conjur
          # The authn-jwt service ID
          serviceID: {{JWT_SERVICE_ID}}
          # Service account to retrieve JWT token for
          serviceAccountRef:
            name: {{JWT_SERVICE_ACCOUNT}}
            audiences:
              - conjur
