---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: db-credentials
spec:
  provider: conjur
  parameters:
    conjur.org/configurationVersion: 0.1.0
    account: conjur
    applianceUrl: 
    authnId: authn-jwt/
    sslCertificate: | 
      -----BEGIN CERTIFICATE-----
      MIIDPzCCAiegAwIBAgIVAKgk7zZmHrsi/6faZA1TO39RVMBCMA0GCSqGSIb3DQEB
      CwUAMDsxDDAKBgNVBAoMA2RldjESMBAGA1UECwwJQ29uanVyIENBMRcwFQYDVQQD
      DA5jeWJyc2VsZnNlcnZlcjAeFw0yNDA3MTYxNTEwNDFaFw0zNDA3MTQxNTEwNDFa
      MBkxFzAVBgNVBAMMDmN5YnJzZWxmc2VydmVyMIIBIjANBgkqhkiG9w0BAQEFAAOC
      AQ8AMIIBCgKCAQEA0JTwlvOcmnzATqYQKZIxYedie9qiVgMt8xHpmW9XBVfK39HK
      vTXavP9sfT2UZ7IcGVLAuQCiwQb0uUZ3hNNloCYsePcN4CkMJEyt0QP1GGWuj1oU
      RMp2vgGjlfWF8uZJVFfnvLnCUucQIBe9WmlGMFC/sBbxh/y9G0KaIxF4YSIDOLJ8
      6MJ9eouktUL2ps9We1ZMDFvKltus5kgWoLVvCdKeD7hLbeXjR1UsyHGZbrCxV6eQ
      4+3m7dKFl/cR8gnFNBIK1uCe+niPl0krjED8Ryk+mU2+V9StlnQrkSfNWGAFO8oZ
      tcDKF7aGqU8uXkisC++Ymtk4ewS1vItplX6MDwIDAQABo1wwWjAOBgNVHQ8BAf8E
      BAMCBaAwHQYDVR0OBBYEFNo5o+5ea0sNMlW/75VgGJCv2AcJMCkGA1UdEQQiMCCC
      DmN5YnJzZWxmc2VydmVygg5jeWJyc2VsZnNlcnZlcjANBgkqhkiG9w0BAQsFAAOC
      AQEAR9PUDitavkKuwe3vshyK5WIu3QHfWXQL93su687ir8E+ji2UBOD2P+qXPcop
      8dTe/q3tVQyPX4m5In5p9p6HKmaP3W6UmiJ5rvbMLH70pM92NWKoKdzEl05ZOsVM
      ndG0xmxmLAwLPQFltC1Y3fCEw0rZ9pKK/j1/pCetCpmjEb6jdFj5wv8/rSM2HQUN
      mU4xPBrbmcmEd3dCU/N+oKtGGwLp+1zdtSTAs3Eiluo08H0v2qs5Z5qr5Nc1L9pk
      xBMuqu/ayLMe2ydsy4W6DRmlAJpfDNIQMAJe8lClmf1eoBh8uZhl9aq2lzdeFo3s
      9zoz6xj6+RK1CaQFNN/8K7ARWA==
      -----END CERTIFICATE-----
    secrets: |
      - DB_HOSTNAME: data/vault///address
      - DB_NAME: data/vault///Database
      - DB_UNAME: data/vault///username
      - DB_PWD: data/vault///password
